import json, copy

with open("workbook_content.json", "r", encoding="utf-8-sig") as f:
    data = json.load(f)

# 40 Block G entries: 8 weeks x 5 days
# Progressive handwriting curriculum with confidence-building pedagogy
block_g_data = [
  # WEEK 1: Letter Formation Foundations
  {"title":"Pencil Power: Grip & Posture","time":3,"img":"land1_the-classroom.jpg","img_alt":"Children writing at desks in Harmonia","img_source":"SOE Picture Dictionary — Land 1","phonetic":"GRIP | POS-cher | PEN-sul | RITE | TRAYCE","instructions":"Hold your pencil with thumb and pointer finger, resting on your middle finger. Sit tall, feet flat. Trace the dotted letters A, B, C three times each. Circle your best one!","tip":"Amara says: A strong pencil grip is the first step to confident writing. Your hand is your most powerful tool!"},
  {"title":"Tall Letters: L, T, H, K","time":3,"img":"land1_greetings-introductions.jpg","img_alt":"Tall letter practice in Harmonia school","img_source":"SOE Picture Dictionary — Land 1","phonetic":"LET-er | TALL | LINE | STRAYT | DOWN","instructions":"Tall letters touch the top line! Practice L, T, H, K — trace 3, then write 3 on your own. Write one word starting with each letter. Keep them tall and proud!","tip":"Kwame says: Tall letters stand with confidence — just like you when you know the answer!"},
  {"title":"Round Letters: O, C, G, Q","time":3,"img":"land1_emotions-feelings.jpg","img_alt":"Round letter shapes in Harmonia art room","img_source":"SOE Picture Dictionary — Land 1","phonetic":"ROUND | KER-v | SER-kul | SMOOTH | FLOW","instructions":"Round letters start like a clock — at 2 o'clock, curve left! Practice O, C, G, Q. Trace 3, write 3. Which round letter is hardest? Practice that one 5 more times.","tip":"Amara says: Round letters flow like music — smooth and connected. Let your hand dance!"},
  {"title":"Short Letters: a, e, i, o, u","time":3,"img":"land1_daily-routines.jpg","img_alt":"Lowercase vowels on a Harmonia chalkboard","img_source":"SOE Picture Dictionary — Land 1","phonetic":"VOW-ul | SHORT | LOW-er | SMALL | NEAT","instructions":"Lowercase vowels sit between the middle and bottom lines. Write each vowel 5 times. Then write 5 words that START with a vowel. Keep them small and neat!","tip":"Kwame says: Vowels are the heartbeat of every word. Master them and your writing sings!"},
  {"title":"My Name in Perfect Print","time":3,"img":"land1_personal-information.jpg","img_alt":"Children writing their names proudly in Harmonia","img_source":"SOE Picture Dictionary — Land 1","phonetic":"NAYM | PRINT | CAP-ih-tul | LOW-er | PROUD","instructions":"Write your FULL NAME in your best handwriting — 5 times! Capital first letter, lowercase rest. Decorate your favorite version with a border. This is YOUR signature style!","tip":"Amara says: Your name is the most important word you'll ever write. Make it beautiful — it represents YOU!"},

  # WEEK 2: Spacing & Flow
  {"title":"Finger Spaces Matter","time":3,"img":"land1_family-relationships.jpg","img_alt":"Words with proper spacing in Harmonia notebook","img_source":"SOE Picture Dictionary — Land 1","phonetic":"SPAYS | FIN-ger | BE-tween | WORD | KLEAR","instructions":"Use your pointer finger to make spaces between words! Write: 'I love my family' with perfect finger spaces. Now write 3 sentences about your family with clear spaces.","tip":"Amara says: Finger spaces make your writing readable. If someone can read it easily, you've done it right!"},
  {"title":"Letter Pairs: th, sh, ch","time":3,"img":"land1_pets-at-home.jpg","img_alt":"Digraph letter pairs on a Harmonia poster","img_source":"SOE Picture Dictionary — Land 1","phonetic":"th | sh | ch | PAIR | TO-geth-er","instructions":"Some letters work in pairs! Write th, sh, ch 5 times each. Now write 3 words for each pair (the, she, chin). Underline the letter pairs in each word.","tip":"Kwame says: Letter pairs are best friends that make new sounds together. Listen for them everywhere!"},
  {"title":"Sizing Matters: Big & Small","time":3,"img":"land1_colors-patterns.jpg","img_alt":"Letters in different sizes on colorful paper","img_source":"SOE Picture Dictionary — Land 1","phonetic":"SIZE | BIG | SMALL | CON-sis-tent | EEVEN","instructions":"Write the alphabet — keeping all tall letters the SAME height and all short letters the SAME height. Consistency is the secret to beautiful handwriting!","tip":"Amara says: Consistent letter sizes make your writing look professional. You're becoming a penmanship pro!"},
  {"title":"Descenders: g, j, p, q, y","time":3,"img":"land1_manners-politeness.jpg","img_alt":"Letters that go below the line in Harmonia","img_source":"SOE Picture Dictionary — Land 1","phonetic":"de-SEND-er | BE-low | TAIL | DIP | LINE","instructions":"Some letters have tails that dip BELOW the line! Practice g, j, p, q, y — trace 3, write 5. Write 5 words with descenders. Keep those tails neat!","tip":"Kwame says: Descenders are letters with roots — they reach down deep, just like strong learners!"},
  {"title":"Copying a Sentence Perfectly","time":3,"img":"land1_hobbies-recreation.jpg","img_alt":"Perfect sentence copying in Harmonia study hall","img_source":"SOE Picture Dictionary — Land 1","phonetic":"KOP-ee | SEN-tens | PER-fekt | CARE-ful | MATCH","instructions":"Copy this sentence in your BEST writing: 'Every great journey begins with a single step.' Compare yours to the original — spacing, sizing, neatness. Rate yourself 1-5!","tip":"Amara says: Careful copying trains your hand and eye to work together. Precision builds confidence!"},

  # WEEK 3: Words & Connections
  {"title":"Writing Sight Words Beautifully","time":3,"img":"land1_the-neighborhood.jpg","img_alt":"Sight words displayed beautifully in Harmonia","img_source":"SOE Picture Dictionary — Land 1","phonetic":"SITE | WORD | PRAK-tis | MEM-oh-ree | HAND","instructions":"Write these 10 sight words in your best handwriting: the, and, is, was, are, have, they, from, with, said. Circle the 3 you wrote best. Practice the 3 hardest again.","tip":"Amara says: When sight words flow from your hand automatically, your brain is free to think bigger thoughts!"},
  {"title":"Speed vs. Neatness Balance","time":3,"img":"land1_communication-technology.jpg","img_alt":"Fast and neat writing comparison in Harmonia","img_source":"SOE Picture Dictionary — Land 1","phonetic":"SPEED | NEAT | BAL-ans | KWIK | CARE","instructions":"Write 'The quick brown fox jumps over the lazy dog' (it has every letter!) slowly and beautifully. Then write it fast. Compare! Find YOUR best speed-neatness balance.","tip":"Kwame says: The goal isn't slow OR fast — it's finding YOUR rhythm where speed meets beauty!"},
  {"title":"Connecting Letters Smoothly","time":3,"img":"land1_music-instruments.jpg","img_alt":"Flowing connected letters like music notes","img_source":"SOE Picture Dictionary — Land 1","phonetic":"con-NEKT | FLOW | SMOOTH | LINK | KUR-siv","instructions":"Practice connecting letter pairs: an, at, in, on, up, it. Write each pair 5 times without lifting your pencil. Then write 5 short words in one smooth stroke each!","tip":"Amara says: Connected letters flow like a melody — each note leads naturally to the next!"},
  {"title":"Writing a Full Address","time":3,"img":"land6_safety-emergencies.jpg","img_alt":"Address writing practice in Luminosity","img_source":"SOE Picture Dictionary — Land 6","phonetic":"AD-res | STREET | SIT-ee | STATE | ZIP","instructions":"Write your full home address in your neatest handwriting — 3 times. Include: name, street, city, state, ZIP. This is a life skill AND a penmanship exercise!","tip":"Felix says: Being able to write your address clearly could help you in an emergency. Neat writing saves lives!"},
  {"title":"Handwriting Self-Assessment","time":3,"img":"land1_the-playground-recess.jpg","img_alt":"Children reviewing their writing progress","img_source":"SOE Picture Dictionary — Land 1","phonetic":"A-SES | IM-proov | GROW | RATE | GOAL","instructions":"Look at your writing from Week 1 vs. now. Rate yourself 1-5 on: letter size, spacing, neatness, speed, confidence. Write 1 goal for next week's handwriting.","tip":"Kwame says: Self-assessment is how champions grow. Be honest AND kind with yourself!"},

  # WEEK 4: Sentences & Punctuation
  {"title":"Punctuation Penmanship","time":3,"img":"land1_celebrations-traditions.jpg","img_alt":"Punctuation marks as decorations in Harmonia","img_source":"SOE Picture Dictionary — Land 1","phonetic":"PER-ee-od | KWEST-yun | EX-klam | KOM-uh | AH-pos-troh-fee","instructions":"Practice writing punctuation marks: . ? ! , ' — each one 10 times. Write 5 sentences using different end marks. Make each mark CLEAR and perfectly placed!","tip":"Amara says: Punctuation marks are the traffic signals of writing. Without them, readers get lost!"},
  {"title":"Numbers in Handwriting","time":3,"img":"land2_numbers-counting.jpg","img_alt":"Handwritten numbers in Numeria","img_source":"SOE Picture Dictionary — Land 2","phonetic":"NUM-ber | DIG-it | HAND-rite | KLEAR | MATCH","instructions":"Write numbers 0-20 in your best handwriting. Then write your birthday as a full date. Write 3 math equations and their answers — all by hand, all neat!","tip":"Kwame says: Handwritten numbers must be crystal clear. A messy 6 that looks like a 0 changes everything!"},
  {"title":"Writing Lists Neatly","time":3,"img":"land1_days-months-numbers.jpg","img_alt":"Organized handwritten lists in Harmonia","img_source":"SOE Picture Dictionary — Land 1","phonetic":"LIST | OR-der | BUL-let | NUM-berd | OR-gan-ized","instructions":"Write a numbered list of the 7 days of the week AND the 12 months. Keep alignment perfect — numbers lined up, letters starting at the same point. Neat lists = organized minds!","tip":"Amara says: A neatly written list is a sign of an organized thinker. Lists are thinking tools!"},
  {"title":"Copying a Short Poem","time":3,"img":"land1_the-home.jpg","img_alt":"Poetry in beautiful handwriting in Harmonia","img_source":"SOE Picture Dictionary — Land 1","phonetic":"PO-em | KOP-ee | LEEN | VERS | BYOO-tih-ful","instructions":"Copy this poem in your best writing: 'I am a learner, bold and bright / I write my words with care and might / Each letter placed with steady hand / I'm growing strong across the land.' Decorate the border!","tip":"Kwame says: Copying poetry trains your hand to feel the rhythm of beautiful language!"},
  {"title":"Midpoint Handwriting Check","time":3,"img":"land7_the-scientific-method.jpg","img_alt":"Writing assessment in Celestia review hall","img_source":"SOE Picture Dictionary — Land 7","phonetic":"MID-poynt | CHECK | PRO-gres | GROW | NEXT","instructions":"Halfway handwriting review! Write your name, address, and 3 sentences about summer — all in your ABSOLUTE best. Compare to Week 1. See the growth? You should be PROUD!","tip":"Ezra says: Halfway through and your handwriting has transformed! Growth is visible when you look back!"},

  # WEEK 5: Expression & Style
  {"title":"Handwriting & Breathing","time":3,"img":"land5_mental-health-emotions.jpg","img_alt":"Mindful writing practice in Vitalis","img_source":"SOE Picture Dictionary — Land 5","phonetic":"BREETH | SLOW | MIND-ful | STEAD-ee | KAM","instructions":"Breathe in for 4 counts, write one letter on the exhale. Slowly spell: C-O-N-F-I-D-E-N-C-E. Each letter made with full calm attention. Notice how different this feels!","tip":"Octavia says: Mindful handwriting calms your nervous system. It's meditation with a pencil!"},
  {"title":"Writing With Feeling","time":3,"img":"land5_meal-time.jpg","img_alt":"Expressive handwriting samples in Vitalis","img_source":"SOE Picture Dictionary — Land 5","phonetic":"FEEL | EX-press | BOLD | JEN-tul | STRONG","instructions":"Write 'I AM STRONG' in big, bold letters. Write 'I am calm' in small, gentle letters. Write 'I am EXCITED!' with energy. Your handwriting can SHOW emotion. Try 3 more feelings!","tip":"Amara says: Handwriting is self-expression — your personality flows through your pen!"},
  {"title":"Decorative First Letters","time":3,"img":"land7_inventions-discoveries.jpg","img_alt":"Illuminated letters in Celestia manuscript room","img_source":"SOE Picture Dictionary — Land 7","phonetic":"DEK-or-ay-tiv | FURST | IL-oo-mih-nay-ted | FAYN-see | ART","instructions":"Medieval scribes made the first letter of each chapter HUGE and decorative. Pick your first initial — draw it large, add patterns, colors, and designs. Make it YOUR masterpiece letter!","tip":"Elias says: For centuries, beautiful first letters were considered an art form. You're continuing a thousand-year tradition!"},
  {"title":"Writing Thank-You Notes","time":3,"img":"land6_job-interview-skills.jpg","img_alt":"Handwritten thank-you cards in Luminosity","img_source":"SOE Picture Dictionary — Land 6","phonetic":"THANK | NOTE | HAND-rit-en | PER-son-ul | CARE","instructions":"Write a real thank-you note to someone who helped you recently. Include: greeting, 2 specific things you're thankful for, a warm closing. Handwritten notes mean MORE than texts!","tip":"Felix says: A handwritten thank-you note is one of the most powerful things you can give someone. It says: you matter enough for my best effort!"},
  {"title":"Speed Writing Sprint","time":3,"img":"land5_sports-fitness.jpg","img_alt":"Writing speed challenge in Vitalis","img_source":"SOE Picture Dictionary — Land 5","phonetic":"SPEED | SPRINT | TIYMD | LEGIBLE | FAST","instructions":"Set a timer for 60 seconds. Write as many complete words as you can — but they must ALL be readable! Count your total. Try again and beat your score while staying neat!","tip":"Nerissa says: Speed writing is a workout for your hand muscles. Like any athlete, practice builds endurance!"},

  # WEEK 6: Creative Lettering
  {"title":"Bubble Letters & Block Letters","time":3,"img":"land7_inventions-discoveries.jpg","img_alt":"Creative lettering styles in Celestia design studio","img_source":"SOE Picture Dictionary — Land 7","phonetic":"BUB-ul | BLOK | STYLE | FONT | CREE-ay-tiv","instructions":"Write your name in 3 styles: regular print, BUBBLE LETTERS (outline and fill), and BLOCK LETTERS (straight edges). Which style represents you best? Color your favorite!","tip":"Elias says: Typography is the art of making letters beautiful. Every font was designed by a human hand first!"},
  {"title":"Writing in Different Sizes","time":3,"img":"land7_ages-life-stages.jpg","img_alt":"Writing at different scales in Celestia","img_source":"SOE Picture Dictionary — Land 7","phonetic":"TYNE-ee | SMALL | MED-ee-um | LARJ | JY-ant","instructions":"Write 'I can write at ANY size' in: tiny (2mm), small (5mm), medium (1cm), large (2cm), and GIANT (fill the whole line). Control at every size = true penmanship mastery!","tip":"Amara says: A master penman can write beautifully at any size. That's real control!"},
  {"title":"Left-to-Right Flow Drills","time":3,"img":"land7_time-in-music-rhythm.jpg","img_alt":"Flowing handwriting patterns like music","img_source":"SOE Picture Dictionary — Land 7","phonetic":"FLOW | PAT-ern | WAVE | LOOP | ZIG-ZAG","instructions":"Fill one line with each pattern: waves ∿∿∿, loops ℓℓℓ, zigzags ⋎⋎⋎, spirals @@@ . These warm up your hand muscles. Then write 3 sentences with smooth, flowing connections.","tip":"Kwame says: Warm-up patterns train your hand muscles the way athletes stretch before a game!"},
  {"title":"Postcard Writing","time":3,"img":"land4_hotels-lodging.jpg","img_alt":"Handwritten postcards from Aquaria travelers","img_source":"SOE Picture Dictionary — Land 4","phonetic":"POST-kard | GREET | WISH | TRAV-el | SHARE","instructions":"Design a postcard: draw a scene on one side, write a message on the other. Include: greeting, 3 sentences about where you are (real or imaginary), closing, your name. Neat and fun!","tip":"Ronan says: Postcards are tiny windows into someone's adventure. Write one that makes the reader smile!"},
  {"title":"Handwriting Portfolio Page","time":3,"img":"land7_inventions-discoveries.jpg","img_alt":"Writing showcase display in Celestia gallery","img_source":"SOE Picture Dictionary — Land 7","phonetic":"PORT-foh-lee-oh | SHOW-kays | BEST | PROUD | GROW","instructions":"Create your Handwriting Portfolio page: write your name, today's date, the alphabet (upper AND lower), one sentence, and one word that describes your writing style. Frame it with a border!","tip":"Ezra says: Your handwriting portfolio shows the world who you are through your letters. Make it shine!"},

  # WEEK 7: Fluency & Storytelling
  {"title":"Writing a Mini Story by Hand","time":3,"img":"land1_greetings-introductions.jpg","img_alt":"Handwritten story pages in Harmonia library","img_source":"SOE Picture Dictionary — Land 1","phonetic":"STOR-ee | HAND-rit-en | CHAR-ak-ter | PLOT | END","instructions":"Write a 5-sentence story entirely by hand. Include: a character, a setting, a problem, a solution, and a lesson. Focus on neat, readable handwriting throughout. Title it at the top!","tip":"Amara says: Handwritten stories carry your personality in every curve and line. No two are alike!"},
  {"title":"Copying a Famous Quote","time":3,"img":"land1_communication-technology.jpg","img_alt":"Inspirational quotes in beautiful handwriting","img_source":"SOE Picture Dictionary — Land 1","phonetic":"KWOTE | FAYE-mus | IN-spyre | KOP-ee | CARE","instructions":"Copy this quote in your finest writing: 'The pen is mightier than the sword.' — Edward Bulwer-Lytton. Then write YOUR OWN quote about learning. Make both beautiful!","tip":"Kwame says: When you write powerful words in beautiful handwriting, the message becomes unforgettable!"},
  {"title":"Writing a Letter to a Friend","time":3,"img":"land1_music-instruments.jpg","img_alt":"Letter writing in Harmonia post office","img_source":"SOE Picture Dictionary — Land 1","phonetic":"LET-er | FREND | DEAR | SIN-seer-lee | YOURS","instructions":"Write a real letter to a friend or family member: Dear ___, (3 paragraphs about your summer, what you've learned, and what you're excited about), closing, signature. Mail it or hand-deliver!","tip":"Amara says: A handwritten letter is a gift that lasts forever. Someone will treasure YOUR words!"},
  {"title":"Cornell Notes by Hand","time":3,"img":"land1_the-classroom.jpg","img_alt":"Organized handwritten notes in Harmonia study room","img_source":"SOE Picture Dictionary — Land 1","phonetic":"NOTE | OR-gan-ize | KEY-word | SUM-air-ize | RITE","instructions":"Take handwritten Cornell Notes on today's favorite activity: draw the line, write details on the right, key words on the left, summary at the bottom. Neat notes = better memory!","tip":"Kwame says: Handwriting notes activates more brain areas than typing. Your hand teaches your brain!"},
  {"title":"Handwriting Fluency Test","time":3,"img":"land1_school-events-activities.jpg","img_alt":"Writing fluency celebration in Harmonia","img_source":"SOE Picture Dictionary — Land 1","phonetic":"FLOO-en-see | SMOOTH | KON-fi-dent | STEAD-ee | MAST-er","instructions":"Write for 2 minutes straight about your favorite summer memory — no stopping, no erasing! Count your words. Is your handwriting still neat at speed? THAT is fluency. You've earned it!","tip":"Amara says: Handwriting fluency means your hand keeps up with your thoughts. That's freedom on paper!"},

  # WEEK 8: Showcase & Legacy
  {"title":"My Signature Style","time":3,"img":"land1_greetings-introductions.jpg","img_alt":"Personal signatures on display in Harmonia","img_source":"SOE Picture Dictionary — Land 1","phonetic":"SIG-nuh-cher | STYLE | PER-son-ul | YOONEEK | OWN","instructions":"Design YOUR personal signature — a stylized version of your name that's uniquely yours. Practice 10 versions. Pick your favorite. This is how you'll sign important documents someday!","tip":"Amara says: Your signature is your personal logo. It says 'I was here, and I matter.' Make it yours!"},
  {"title":"Writing Awards & Certificates","time":3,"img":"land1_personal-information.jpg","img_alt":"Handwritten certificates in Harmonia ceremony","img_source":"SOE Picture Dictionary — Land 1","phonetic":"A-WARD | SER-tif-ih-kit | HON-or | A-CHEEV | PROUD","instructions":"Create a Penmanship Certificate for yourself: 'This certifies that ___ has completed 8 weeks of Handwriting Essentials and is now a Penmanship Champion!' Write it in your absolute BEST handwriting.","tip":"Kwame says: You earned this certificate with 8 weeks of daily practice. Your handwriting tells your story of dedication!"},
  {"title":"Before & After Comparison","time":3,"img":"land7_the-scientific-method.jpg","img_alt":"Growth comparison display in Celestia","img_source":"SOE Picture Dictionary — Land 7","phonetic":"BE-for | AF-ter | GROW | CHAHNJE | PROUD","instructions":"Write the same sentence from Week 1 Day 5: your full name, address, and 'I am a writer.' Compare to your Week 1 version. See the transformation? Write 3 ways your handwriting improved.","tip":"Ezra says: The distance between your first page and this page is called GROWTH. You can see it with your own eyes!"},
  {"title":"Letter to Future Me (Handwritten)","time":3,"img":"land7_the-future-dreams.jpg","img_alt":"Handwritten letters to the future in Celestia","img_source":"SOE Picture Dictionary — Land 7","phonetic":"FU-cher | LET-er | PROM-iss | HAND-rit-en | KEEP","instructions":"Write a handwritten letter to yourself to open on the last day of school. Tell future-you what you learned about handwriting, confidence, and self-expression. Seal it in an envelope!","tip":"Amara says: This letter is written in YOUR hand — no one else in the world writes exactly like you. That's beautiful!"},
  {"title":"🏆 Grand Penmanship Showcase","time":3,"img":"land7_the-future-dreams.jpg","img_alt":"Grand handwriting showcase in Celestia celebration hall","img_source":"SOE Picture Dictionary — All Lands","phonetic":"SHOW-kays | CHAMP-ee-on | MAS-ter | PROUD | FOR-ev-er","instructions":"Final showcase: Write the Summer Stretch Champion Pledge in your most beautiful handwriting: 'I pledge to write with confidence, care, and creativity. My handwriting is my voice on paper. I am a Penmanship Champion!' Sign and date it.","tip":"All Heroes say: Your handwriting journey has transformed you from a writer into an ARTIST of words. Carry this confidence into everything you write!"}
]

# Inject Block G into every day
day_index = 0
for week in data["weeks"]:
    for day in week["days"]:
        if day_index < len(block_g_data):
            day["blocks"]["G"] = block_g_data[day_index]
            day_index += 1

print(f"Injected Block G into {day_index} days")

with open("workbook_content.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("✅ workbook_content.json updated successfully!")
